// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfUTEI_cq7ZmMlotL6p6GVOHE_gfJJu4w',
    appId: '1:408695213199:web:2c509a560598d1c6cff4fa',
    messagingSenderId: '408695213199',
    projectId: 'kornia-89399',
    authDomain: 'kornia-89399.firebaseapp.com',
    storageBucket: 'kornia-89399.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkC5w8E3czJGWG3OIxiJ3G9u8IBI6YXQg',
    appId: '1:408695213199:android:9cac79e7c9a03956cff4fa',
    messagingSenderId: '408695213199',
    projectId: 'kornia-89399',
    storageBucket: 'kornia-89399.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBonhOQFqlSYWBKRckZ9m-kYS8eX59WttI',
    appId: '1:408695213199:ios:05efb91eeb2a6dbccff4fa',
    messagingSenderId: '408695213199',
    projectId: 'kornia-89399',
    storageBucket: 'kornia-89399.firebasestorage.app',
    iosBundleId: 'com.example.kornia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfUTEI_cq7ZmMlotL6p6GVOHE_gfJJu4w',
    appId: '1:408695213199:web:b5b57e33a4b26484cff4fa',
    messagingSenderId: '408695213199',
    projectId: 'kornia-89399',
    authDomain: 'kornia-89399.firebaseapp.com',
    storageBucket: 'kornia-89399.firebasestorage.app',
  );
}
